project_id = "sutmmlryzosbasksamqw"

[functions.bootstrap-admin]
verify_jwt = false

[functions.setup-complete-system]
verify_jwt = false

[functions.admin-update-password]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false
